# change_assurance/domains/cloud/config_prerequisites.py
# AWS Config dedicated-prerequisite artifact generator.
# Manager must explicitly choose CREATE_DEDICATED. Never applies to AWS.

from __future__ import annotations

from typing import Any

VERSION = "0.2.0"

CHOICE_CREATE_DEDICATED = "CREATE_DEDICATED"
CHOICE_REUSE = "REUSE_EXISTING"

COST_NOTE = (
    "AWS Config can generate usage charges for configuration recording, "
    "configuration items, and related Config features. Confirm budget/owner "
    "acceptance before human-triggered apply."
)

REQUIRED_REMEDIATION_ROLE_PERMISSIONS = [
    {
        "action": "iam:CreateServiceLinkedRole",
        "scope": "Restricted to ServiceName=config.amazonaws.com",
        "why": "Create AWSServiceRoleForConfig when absent",
    },
    {
        "action": "iam:GetRole",
        "scope": "AWSServiceRoleForConfig",
        "why": "Read service-linked role after create",
    },
    {
        "action": "config:PutConfigurationRecorder",
        "scope": "Account/Region recorder sentinel-recorder",
        "why": "Create/update configuration recorder",
    },
    {
        "action": "config:PutDeliveryChannel",
        "scope": "Account/Region delivery channel sentinel-delivery",
        "why": "Create/update delivery channel",
    },
    {
        "action": "config:StartConfigurationRecorder",
        "scope": "sentinel-recorder",
        "why": "Enable recorder status",
    },
    {
        "action": "config:DescribeConfigurationRecorders",
        "scope": "Region",
        "why": "Validate recorder after apply",
    },
    {
        "action": "config:DescribeConfigurationRecorderStatus",
        "scope": "Region",
        "why": "Confirm recording=true",
    },
    {
        "action": "s3:CreateBucket",
        "scope": "Dedicated sentinel-aws-config-<account>-<region> bucket only",
        "why": "Create Config delivery bucket",
    },
    {
        "action": "s3:PutBucketPublicAccessBlock",
        "scope": "Dedicated Config bucket",
        "why": "Block public access",
    },
    {
        "action": "s3:PutEncryptionConfiguration",
        "scope": "Dedicated Config bucket",
        "why": "Enable SSE-S3",
    },
    {
        "action": "s3:PutBucketOwnershipControls",
        "scope": "Dedicated Config bucket",
        "why": "Bucket owner preferred for service delivery",
    },
    {
        "action": "s3:PutBucketPolicy",
        "scope": "Dedicated Config bucket",
        "why": "Least-privilege Config delivery policy",
    },
    {
        "action": "s3:GetBucketPolicy",
        "scope": "Dedicated Config bucket",
        "why": "Readback during plan/apply",
    },
    {
        "action": "s3:PutBucketVersioning",
        "scope": "Dedicated Config bucket",
        "why": "Enable versioning for Config delivery durability / recoverability",
    },
]

DO_NOT_TOUCH = [
    "aws-cloudtrail-logs-952654481542-06ac3f84",
    "Existing CloudTrail bucket policy / cloudtrail.amazonaws.com grants",
    "GuardDuty detectors",
    "IAM users / password policies",
    "Application workloads (Config records; it does not auto-remediate resources)",
]

EXPECTED_RESOURCES = [
    "aws_iam_service_linked_role.config",
    "data.aws_caller_identity.current",
    "data.aws_region.current",
    "aws_s3_bucket.config",
    "aws_s3_bucket_versioning.config",
    "aws_s3_bucket_public_access_block.config",
    "aws_s3_bucket_server_side_encryption_configuration.config",
    "aws_s3_bucket_ownership_controls.config",
    "aws_s3_bucket_policy.config",
    "aws_config_configuration_recorder.sentinel",
    "aws_config_delivery_channel.sentinel",
    "aws_config_configuration_recorder_status.sentinel",
]


def render_dedicated_terraform(*, check_id: str = "CLOUD-LOG-002", version: str = VERSION) -> str:
    """Complete dedicated Config prerequisites — no REPLACE_*/TODO/CHANGEME."""
    return f'''# {check_id} — AWS Config recorder enabled (CREATE DEDICATED prerequisites)
# Generated by Sentinel Stacks prerequisite resolver {version}
#
# Manager decision: CREATE_DEDICATED
# - Creates AWSServiceRoleForConfig (service-linked role)
# - Creates dedicated encrypted/private Config delivery bucket
# - Enables S3 versioning on the Config delivery bucket (audit durability)
# - Does NOT enable MFA Delete (root/MFA-only AWS operation; MANUAL-ONLY)
# - Does NOT modify existing CloudTrail buckets
# dry_run / no auto-apply: human must terraform plan + approve + apply

data "aws_caller_identity" "current" {{}}
data "aws_region" "current" {{}}

resource "aws_iam_service_linked_role" "config" {{
  aws_service_name = "config.amazonaws.com"
}}

resource "aws_s3_bucket" "config" {{
  bucket = "sentinel-aws-config-${{data.aws_caller_identity.current.account_id}}-${{data.aws_region.current.region}}"

  tags = {{
    Name               = "sentinel-aws-config"
    SentinelControl    = "{check_id}"
    SentinelPurpose    = "aws-config-delivery"
    DoNotReuseForTrail = "true"
  }}
}}

resource "aws_s3_bucket_versioning" "config" {{
  bucket = aws_s3_bucket.config.id

  versioning_configuration {{
    status = "Enabled"
    # MFA Delete intentionally omitted: AWS requires root + MFA serial/token.
    # Sentinel marks MFA Delete as MANUAL-ONLY / NOT APPLICABLE for automated remediation.
  }}
}}

resource "aws_s3_bucket_public_access_block" "config" {{
  bucket = aws_s3_bucket.config.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}

resource "aws_s3_bucket_server_side_encryption_configuration" "config" {{
  bucket = aws_s3_bucket.config.id

  rule {{
    apply_server_side_encryption_by_default {{
      sse_algorithm = "AES256"
    }}
  }}
}}

resource "aws_s3_bucket_ownership_controls" "config" {{
  bucket = aws_s3_bucket.config.id

  rule {{
    object_ownership = "BucketOwnerPreferred"
  }}
}}

resource "aws_s3_bucket_policy" "config" {{
  bucket = aws_s3_bucket.config.id

  depends_on = [
    aws_s3_bucket_public_access_block.config,
    aws_s3_bucket_ownership_controls.config,
  ]

  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Sid       = "AWSConfigBucketPermissionsCheck"
        Effect    = "Allow"
        Principal = {{ Service = "config.amazonaws.com" }}
        Action    = "s3:GetBucketAcl"
        Resource  = aws_s3_bucket.config.arn
        Condition = {{
          StringEquals = {{
            "AWS:SourceAccount" = data.aws_caller_identity.current.account_id
          }}
        }}
      }},
      {{
        Sid       = "AWSConfigBucketExistenceCheck"
        Effect    = "Allow"
        Principal = {{ Service = "config.amazonaws.com" }}
        Action    = "s3:ListBucket"
        Resource  = aws_s3_bucket.config.arn
        Condition = {{
          StringEquals = {{
            "AWS:SourceAccount" = data.aws_caller_identity.current.account_id
          }}
        }}
      }},
      {{
        Sid       = "AWSConfigBucketDelivery"
        Effect    = "Allow"
        Principal = {{ Service = "config.amazonaws.com" }}
        Action    = "s3:PutObject"
        Resource  = "${{aws_s3_bucket.config.arn}}/AWSLogs/${{data.aws_caller_identity.current.account_id}}/Config/*"
        Condition = {{
          StringEquals = {{
            "s3:x-amz-acl"      = "bucket-owner-full-control"
            "AWS:SourceAccount" = data.aws_caller_identity.current.account_id
          }}
        }}
      }}
    ]
  }})
}}

resource "aws_config_configuration_recorder" "sentinel" {{
  name     = "sentinel-recorder"
  role_arn = aws_iam_service_linked_role.config.arn

  recording_group {{
    all_supported                 = true
    include_global_resource_types = true
  }}

  depends_on = [
    aws_iam_service_linked_role.config,
    aws_s3_bucket_policy.config,
  ]
}}

resource "aws_config_delivery_channel" "sentinel" {{
  name           = "sentinel-delivery"
  s3_bucket_name = aws_s3_bucket.config.bucket

  depends_on = [aws_config_configuration_recorder.sentinel]
}}

resource "aws_config_configuration_recorder_status" "sentinel" {{
  name       = aws_config_configuration_recorder.sentinel.name
  is_enabled = true

  depends_on = [aws_config_delivery_channel.sentinel]
}}
'''


def render_dedicated_runbook(*, check_id: str = "CLOUD-LOG-002", region: str = "us-east-1") -> str:
    return f'''# {check_id} — AWS Config recorder enabled
# Severity: high
# Prerequisite decision: CREATE_DEDICATED
# Human review required. dry_run — does NOT auto-apply.

apiVersion: sentinel-stacks/v1
kind: HardeningRunbook
metadata:
  check_id: "{check_id}"
  title: "AWS Config recorder enabled"
  severity: "high"
  category: "Cloud/Logging"
  region: "{region}"
  dry_run: true
  requires_approval: true
  prerequisite_decision: "CREATE_DEDICATED"
spec:
  how_to_use: |
    1. Confirm manager chose CREATE DEDICATED AWS Config prerequisites.
    2. Review terraform/{check_id}.tf (service-linked role, dedicated bucket, recorder).
    3. terraform validate then terraform plan — expect creates only, no destroys.
    4. Manager approves the exact plan. Human triggers apply. Sentinel does not auto-apply.
    5. Verify Config APIs, then re-scan so {check_id} clears.
  why_it_matters: |
    Without an AWS Config recorder, configuration history and drift evidence are incomplete.
    Dedicated prerequisites avoid modifying the existing CloudTrail delivery bucket.
  cost_note: |
    {COST_NOTE}
  do_not_touch:
    - Existing CloudTrail bucket aws-cloudtrail-logs-* (do not reuse or modify)
    - GuardDuty
    - IAM users / passwords
    - Application resources (Config records; it does not auto-fix them)
  linked_kit_files:
    - "runbooks/{check_id}.yml"
    - "terraform/{check_id}.tf"
  platforms:
    - "terraform"
    - "aws-config"
  prechecks:
    - Confirm Region {region}
    - Confirm describe_configuration_recorders returns empty / not recording
    - Confirm prerequisite decision = CREATE_DEDICATED (explicit, not inferred)
    - Confirm CloudTrail bucket will not be modified
  steps:
    - step: 1
      action: Confirm region {region}.
      detail: Work only in the finding Region. Config recorder and SLR behavior are regional/account-scoped as designed.
      why: Wrong Region wastes effort and confuses verification.
    - step: 2
      action: Confirm direct evidence shows no recorder.
      detail: configservice.describe_configuration_recorders should show ConfigurationRecorders = [] (or not recording).
      why: Only CONFIRMED / DIRECT FAIL justifies creating Config infrastructure.
    - step: 3
      action: Confirm manager chose dedicated prerequisites.
      detail: Job metadata prerequisite_decisions.{check_id}.choice must be CREATE_DEDICATED.
      why: Sentinel must not invent reuse vs create.
    - step: 4
      action: Review AWS Config service-linked role creation.
      detail: terraform resource aws_iam_service_linked_role.config with aws_service_name = config.amazonaws.com (AWSServiceRoleForConfig).
      why: Supported Config role; avoid broad custom roles.
    - step: 5
      action: Review dedicated Config S3 bucket, public access block, encryption, ownership, and Config-only bucket policy.
      detail: Bucket name sentinel-aws-config-$account-$region. Policy principal config.amazonaws.com with AWS:SourceAccount and PutObject path AWSLogs/$account/Config/*.
      why: Least-privilege delivery without touching CloudTrail buckets.
    - step: 6
      action: Run terraform validate.
      detail: From the kit terraform working directory containing {check_id}.tf.
      why: Catch syntax/provider errors before plan.
    - step: 7
      action: Run terraform plan.
      detail: Expect creates for SLR, bucket/security/policy, recorder, delivery channel, recorder status. No destroys on a clean first deploy.
      why: Manager must see exact blast radius before approval.
    - step: 8
      action: Confirm expected resources and no unexpected destroys.
      detail: Compare plan to manifest expected_resources. Reject unexpected IAM/S3/Config deletes.
      why: Protect unrelated CloudTrail and app resources.
    - step: 9
      action: Manager approves the exact plan.
      detail: Face Approve authorizes this reviewed change only — it does not deploy.
      why: Approve ≠ execute.
    - step: 10
      action: Human triggers Terraform apply.
      detail: Operator runs apply with an approved remediation identity. Sentinel does not auto-apply.
      why: Human-in-the-loop execution.
    - step: 11
      action: Verify describe-configuration-recorders.
      detail: Expect sentinel-recorder present in {region}.
      why: API proof of recorder existence.
    - step: 12
      action: Verify describe-configuration-recorder-status shows recording=true.
      detail: Recorder status must be enabled/recording.
      why: Delivery channel + status complete the control.
    - step: 13
      action: Re-run Sentinel Cloud scan.
      detail: Same Cloud Security Agent / scan_cloud_pack path.
      why: Scanner must clear the finding.
    - step: 14
      action: Confirm {check_id} clears.
      detail: Finding no longer FAIL for Config recorder enabled.
      why: Control closed only after re-scan evidence.
    - step: 15
      action: Create verified Casebook entry.
      detail: Archive verified remediation with evidence after clear.
      why: Audit trail for portfolio / interview.
  validation:
    - configservice.describe_configuration_recorders
    - configservice.describe_configuration_recorder_status (recording=true)
    - Re-scan {check_id} no longer fails
  success_looks_like: |
    Recorder present and recording in {region}; {check_id} cleared on re-scan; Casebook entry created.
  rollback: |
    Disable recorder status, remove delivery channel/recorder via Terraform destroy for these resources only,
    then decide whether to retain the dedicated Config bucket. Do not alter CloudTrail buckets.
'''


def resolve_aws_config_dedicated(finding: dict[str, Any], decision_ctx: dict[str, Any]) -> dict[str, Any] | None:
    choice = str(decision_ctx.get("choice") or "")
    if choice == CHOICE_REUSE:
        # Reuse path still requires explicit ARNs — not implemented as silent invent.
        return {
            "resolver": "aws_config_reuse",
            "prerequisite_status": "PREREQUISITES_REQUIRED",
            "message": (
                "REUSE_EXISTING requires manager-supplied role ARN and bucket name; "
                "artifacts not auto-filled."
            ),
            "terraform": None,
            "runbook": None,
            "auto_apply_forbidden": True,
            "execution_performed": False,
        }
    if choice != CHOICE_CREATE_DEDICATED:
        return None

    fid = str(finding.get("id") or "CLOUD-LOG-002")
    region = str(decision_ctx.get("region") or "us-east-1")
    version = str(decision_ctx.get("version") or VERSION)
    return {
        "resolver": "aws_config_create_dedicated",
        "prerequisite_status": "PREREQUISITES_RESOLVED",
        "terraform": render_dedicated_terraform(check_id=fid, version=version),
        "runbook": render_dedicated_runbook(check_id=fid, region=region),
        "expected_resources": list(EXPECTED_RESOURCES),
        "do_not_touch": list(DO_NOT_TOUCH),
        "required_remediation_role_permissions": list(REQUIRED_REMEDIATION_ROLE_PERMISSIONS),
        "cost_note": COST_NOTE,
        "what_will_change": (
            f"Create AWS Config service-linked role, dedicated delivery bucket/policy, "
            f"recorder, delivery channel, and enable recording in {region}."
        ),
        "what_will_not_change": list(DO_NOT_TOUCH),
        "manager_summary": {
            "prerequisite_decision": "CREATE_DEDICATED_RESOURCES",
            "prepare": [
                "AWS Config service-linked role (config.amazonaws.com)",
                "dedicated encrypted/private S3 delivery bucket",
                "S3 versioning on the Config delivery bucket",
                "Config bucket policy",
                "configuration recorder",
                "delivery channel",
                "recorder enablement",
            ],
            "does_not_apply_automatically": True,
        },
        "auto_apply_forbidden": True,
        "execution_performed": False,
    }
