# change_assurance/domains/cloud/guardduty_prerequisites.py
# GuardDuty remediation prerequisites — permission probe + least-privilege IAM artifact.
# Never attaches IAM policies. Never enables GuardDuty. Never applies Terraform.

from __future__ import annotations

import json
from typing import Any

VERSION = "0.2.0-gd-prereq"

# Exact permissions required to apply:
#   resource "aws_guardduty_detector" "sentinel" { enable = true }
# Derived from Terraform AWS provider create/read/update path + AWS GuardDuty first-enable SLR.
# Tags are not set in the current artifact; TagResource/ListTagsForResource retained for
# provider refresh/default_tags compatibility (mirrors Access Analyzer style).
REQUIRED_GUARDDUTY_ACTIONS: tuple[str, ...] = (
    "guardduty:CreateDetector",
    "guardduty:GetDetector",
    "guardduty:ListDetectors",
    "guardduty:UpdateDetector",
    "guardduty:TagResource",
    "guardduty:ListTagsForResource",
)

# First enable in an account creates AWSServiceRoleForAmazonGuardDuty when absent.
REQUIRED_SLR_ACTIONS: tuple[str, ...] = (
    "iam:CreateServiceLinkedRole",
    "iam:GetRole",
)

REQUIRED_REMEDIATION_ROLE_PERMISSIONS: tuple[str, ...] = (
    REQUIRED_GUARDDUTY_ACTIONS + REQUIRED_SLR_ACTIONS
)

REQUIRED_VERIFICATION_PERMISSIONS: tuple[str, ...] = (
    "guardduty:ListDetectors",
    "guardduty:GetDetector",
)

INLINE_POLICY_NAME = "SentinelGuardDutyRemediation"
ROLE_NAME = "SentinelStacksRemediationRole"

# Prefer scanner/read identity for IAM SimulatePrincipalPolicy (remediation role lacks it).
DEFAULT_PROBE_PROFILES: tuple[str, ...] = (
    "sentinel-demo",
    "sentinel-agent",
)


def render_guardduty_inline_policy_document(*, account_id: str, region: str) -> dict[str, Any]:
    """Least-privilege inline policy mirroring Config/Access Analyzer remediation style."""
    slr_arn = (
        f"arn:aws:iam::{account_id}:role/aws-service-role/"
        "guardduty.amazonaws.com/AWSServiceRoleForAmazonGuardDuty"
    )
    return {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "CreateAndManageGuardDutyDetector",
                "Effect": "Allow",
                "Action": list(REQUIRED_GUARDDUTY_ACTIONS),
                "Resource": "*",
                "Condition": {"StringEquals": {"aws:RequestedRegion": region}},
            },
            {
                "Sid": "CreateGuardDutyServiceLinkedRole",
                "Effect": "Allow",
                "Action": "iam:CreateServiceLinkedRole",
                "Resource": "*",
                "Condition": {
                    "StringEquals": {"iam:AWSServiceName": "guardduty.amazonaws.com"}
                },
            },
            {
                "Sid": "ReadAndPassGuardDutyServiceLinkedRole",
                "Effect": "Allow",
                "Action": ["iam:GetRole", "iam:ListRoleTags", "iam:PassRole"],
                "Resource": slr_arn,
                "Condition": {
                    "StringEqualsIfExists": {
                        "iam:PassedToService": "guardduty.amazonaws.com"
                    }
                },
            },
        ],
    }


def render_guardduty_iam_prerequisite_terraform(
    *,
    check_id: str = "CLOUD-LOG-003",
    account_id: str = "952654481542",
    region: str = "us-east-1",
    role_name: str = ROLE_NAME,
    version: str = VERSION,
) -> str:
    """Terraform for Stage A — attach GuardDuty remediation inline policy. Never auto-applied."""
    doc = render_guardduty_inline_policy_document(account_id=account_id, region=region)
    doc_json = json.dumps(doc, indent=2)
    # Escape for HCL heredoc
    return f'''# {check_id} — Stage A: GuardDuty remediation-role permission prerequisite
# Generated by Sentinel Stacks GuardDuty prerequisite preparer {version}
#
# PURPOSE: Grant SentinelStacksRemediationRole least-privilege GuardDuty enablement.
# Does NOT enable GuardDuty itself (Stage B: terraform/CLOUD-LOG-003.tf).
# Does NOT use guardduty:*.
# dry_run / no auto-apply: manager must approve; human-triggered apply only.
#
# APPLY NOTE: iam:PutRolePolicy on the remediation role is required to attach this
# inline policy. SentinelStacksRemediationRole cannot modify its own inline policies
# (SimulatePrincipalPolicy = implicitDeny). Stage A apply identity must hold
# iam:PutRolePolicy on role/{role_name}. Stage B then uses the remediation role.

resource "aws_iam_role_policy" "sentinel_guardduty_remediation" {{
  name = "{INLINE_POLICY_NAME}"
  role = "{role_name}"

  policy = <<EOF
{doc_json}
EOF
}}
'''


def guardduty_permission_assessment(
    *,
    execution_role: str | None = None,
    execution_identity: str | None = None,
    simulated: dict[str, str] | None = None,
    probe_error: str | None = None,
    probe_profile: str | None = None,
    slr_exists: bool | None = None,
) -> dict[str, Any]:
    """
    Assess whether the intended remediation identity can enable GuardDuty.
    simulated maps action → Allow|Deny|ImplicitDeny|Unknown from IAM SimulatePrincipalPolicy.
    """
    role = (execution_role or "").strip() or ROLE_NAME
    identity = (execution_identity or "").strip() or f"arn:aws:iam::unknown:role/{role}"
    sim = dict(simulated or {})
    missing: list[str] = []
    allowed: list[str] = []
    unknown: list[str] = []
    for action in REQUIRED_REMEDIATION_ROLE_PERMISSIONS:
        # SLR Create only required when SLR absent
        if action == "iam:CreateServiceLinkedRole" and slr_exists is True:
            allowed.append(action)
            continue
        decision = str(sim.get(action) or "Unknown")
        if decision.lower() == "allow":
            allowed.append(action)
        elif decision.lower() in {"deny", "implicitdeny", "explicitdeny"}:
            missing.append(action)
        else:
            unknown.append(action)

    if not sim and probe_error:
        status = "UNKNOWN"
        ready = False
        result = "UNKNOWN"
        detail = (
            f"IAM permission probe failed: {probe_error}. "
            "Sentinel could not prove GuardDuty write readiness."
        )
    elif not sim:
        status = "UNKNOWN"
        ready = False
        result = "UNKNOWN"
        detail = (
            "Remediation-role GuardDuty write permissions were not probed — "
            "no SimulatePrincipalPolicy result available."
        )
    elif missing:
        status = "MISSING_PERMISSIONS"
        ready = False
        result = "FAIL"
        detail = (
            f"PERMISSION_READY=FAIL: remediation role lacks GuardDuty enablement permission(s): "
            f"{', '.join(missing)}"
        )
    elif unknown:
        status = "PARTIAL_UNKNOWN"
        ready = False
        result = "UNKNOWN"
        detail = f"Unable to confirm permission(s): {', '.join(unknown)}"
    else:
        status = "READY"
        ready = True
        result = "PASS"
        detail = (
            "PERMISSION_READY=PASS: intended remediation identity allows GuardDuty detector enablement"
        )

    return {
        "version": VERSION,
        "service": "guardduty",
        "execution_role": role,
        "execution_identity": identity,
        "required_remediation_role_permissions": list(REQUIRED_REMEDIATION_ROLE_PERMISSIONS),
        "required_guardduty_actions": list(REQUIRED_GUARDDUTY_ACTIONS),
        "required_slr_actions": list(REQUIRED_SLR_ACTIONS),
        "required_verification_permissions": list(REQUIRED_VERIFICATION_PERMISSIONS),
        "inline_policy_name": INLINE_POLICY_NAME,
        "allowed": allowed,
        "missing": missing,
        "unknown": unknown,
        "permission_status": status,
        "permission_ready": result,
        "execution_permission_ready": ready,
        "detail": detail,
        "probe_profile": probe_profile,
        "slr_exists": slr_exists,
        "aws_modified": False,
        "policy_auto_attached": False,
        "staged_prerequisite": result == "FAIL",
    }


def probe_guardduty_permissions_via_iam(
    *,
    profile: str | None,
    region: str,
    source_arn: str,
    probe_profiles: list[str] | None = None,
) -> tuple[dict[str, str], str | None, str | None]:
    """
    Read-only IAM SimulatePrincipalPolicy for GuardDuty write actions.
    Tries scanner/read profiles first (sentinel-demo) — remediation role typically
    cannot call iam:SimulatePrincipalPolicy on itself.
    Returns (action→decision, probe_profile_used, error_or_none).
    """
    try:
        import boto3
        from botocore.exceptions import ClientError
    except ImportError as e:
        return {}, None, f"boto3 unavailable: {e}"

    candidates: list[str] = []
    for p in list(probe_profiles or []) + list(DEFAULT_PROBE_PROFILES):
        if p and p not in candidates:
            candidates.append(p)
    if profile and profile not in candidates:
        candidates.append(profile)

    last_err: str | None = None
    for prof in candidates:
        try:
            session = boto3.Session(profile_name=prof, region_name=region)
            iam = session.client("iam")
            # Context for GuardDuty SLR create evaluation
            resp = iam.simulate_principal_policy(
                PolicySourceArn=source_arn,
                ActionNames=list(REQUIRED_REMEDIATION_ROLE_PERMISSIONS),
                ContextEntries=[
                    {
                        "ContextKeyName": "iam:AWSServiceName",
                        "ContextKeyValues": ["guardduty.amazonaws.com"],
                        "ContextKeyType": "string",
                    },
                    {
                        "ContextKeyName": "aws:RequestedRegion",
                        "ContextKeyValues": [region],
                        "ContextKeyType": "string",
                    },
                    {
                        "ContextKeyName": "iam:PassedToService",
                        "ContextKeyValues": ["guardduty.amazonaws.com"],
                        "ContextKeyType": "string",
                    },
                ],
            )
            out: dict[str, str] = {}
            for r in resp.get("EvaluationResults") or []:
                action = str(r.get("EvalActionName") or "")
                decision = str(r.get("EvalDecision") or "Unknown")
                if action:
                    out[action] = decision
            if out:
                return out, prof, None
            last_err = f"profile={prof}: empty EvaluationResults"
        except ClientError as e:
            code = (e.response or {}).get("Error", {}).get("Code") or type(e).__name__
            last_err = f"profile={prof}: {code}: {e}"
            continue
        except Exception as e:
            last_err = f"profile={prof}: {type(e).__name__}: {e}"
            continue
    return {}, None, last_err or "no probe profile succeeded"


def check_guardduty_slr_exists(*, profile: str | None, region: str) -> bool | None:
    """Return True/False if SLR existence can be determined; None on probe failure."""
    try:
        import boto3

        session = (
            boto3.Session(profile_name=profile, region_name=region)
            if profile
            else boto3.Session(region_name=region)
        )
        iam = session.client("iam")
        iam.get_role(RoleName="AWSServiceRoleForAmazonGuardDuty")
        return True
    except Exception as e:
        name = type(e).__name__
        text = str(e)
        if "NoSuchEntity" in name or "NoSuchEntity" in text:
            return False
        return None


def prepare_guardduty_permission_package(
    *,
    account_id: str,
    region: str,
    finding_id: str = "CLOUD-LOG-003",
    role_name: str = ROLE_NAME,
) -> dict[str, Any]:
    """Build Stage A artifact content (no AWS writes)."""
    policy_doc = render_guardduty_inline_policy_document(
        account_id=account_id, region=region
    )
    tf = render_guardduty_iam_prerequisite_terraform(
        check_id=finding_id,
        account_id=account_id,
        region=region,
        role_name=role_name,
    )
    return {
        "version": VERSION,
        "stage": "A_IAM_PERMISSION",
        "finding_id": finding_id,
        "role_name": role_name,
        "inline_policy_name": INLINE_POLICY_NAME,
        "policy_document": policy_doc,
        "terraform": tf,
        "terraform_relpath": f"terraform/{finding_id}-iam-prereq.tf",
        "required_actions": list(REQUIRED_REMEDIATION_ROLE_PERMISSIONS),
        "apply_identity_requirement": (
            f"Stage A requires an identity with iam:PutRolePolicy on "
            f"arn:aws:iam::{account_id}:role/{role_name}. "
            f"SentinelStacksRemediationRole cannot attach policies to itself."
        ),
        "stage_b": {
            "artifact": f"terraform/{finding_id}.tf",
            "resource": "aws_guardduty_detector.sentinel",
            "execution_identity": f"arn:aws:iam::{account_id}:role/{role_name}",
        },
        "aws_modified": False,
        "policy_auto_attached": False,
    }
