# ai_remediation_engine.py
# Sentinel Stacks — Remediation Sentinel Module 1: Hardening Kit Engine
# Compliance: TOOL_STANDARDS.md v1.0
# Sovereign: consumes scanner JSON only (no live scanning). Tier 2.
# dry_run=True (default): generate Terraform + YAML + ZIP kit, never apply.

from __future__ import annotations

import datetime
import json
import os
import re
import sys
import zipfile
from pathlib import Path

TOOL_ID = "remediate_findings_hardening_kit"
VERSION = "1.1.0"
DOMAIN = "governance"
SUBDOMAIN = "remediation/hardening-kit"
SENTINEL = "remediation"
TIER = 2
TAGS = [
    "remediation",
    "hardening-kit",
    "terraform",
    "yaml",
    "aws",
    "azure",
    "cis",
    "tier-2",
    "appsec",
    "perimeter",
]

SEV_ORDER = {"critical": 4, "high": 3, "medium": 2, "low": 1, "info": 0}
ACTIONABLE = {"critical", "high", "medium", "low"}


# ═══════════════════════ FIX_MAP (stable control IDs) ═════════════════════════
# Keyed by evidence.check_id / finding.id for AWS-###, AZ-###, GOV-*
# artifact: terraform | runbook | both
# Templates use {resource_id}, {region}, {title}, {check_id}, {severity}

def _fix(
    name: str,
    category: str,
    artifact: str,
    tf: str | None = None,
    yml: str | None = None,
    conf: str | None = None,
    effort: str = "medium",
) -> dict:
    return {
        "name": name,
        "category": category,
        "artifact": artifact,
        "tf": tf,
        "yml": yml,
        "conf": conf,
        "effort": effort,
    }


AWS_TF_IAM_PASSWORD = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}
# REVIEW before apply. dry_run kit — does not mutate cloud by itself.

resource "aws_iam_account_password_policy" "sentinel_hardened" {
  minimum_password_length        = 14
  require_uppercase_characters   = true
  require_lowercase_characters   = true
  require_numbers                = true
  require_symbols                = true
  allow_users_to_change_password = true
  max_password_age               = 90
  password_reuse_prevention      = 24
  hard_expiry                    = false
}
"""

AWS_TF_S3_PUBLIC_BLOCK = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_s3_account_public_access_block" "sentinel_account" {
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Per-bucket example — set bucket name before apply
# resource "aws_s3_bucket_public_access_block" "example" {
#   bucket                  = "REPLACE_BUCKET_NAME"
#   block_public_acls       = true
#   block_public_policy     = true
#   ignore_public_acls      = true
#   restrict_public_buckets = true
# }
"""

AWS_TF_S3_ENCRYPTION = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# Apply per bucket — set name before apply
resource "aws_s3_bucket_server_side_encryption_configuration" "sentinel" {
  bucket = "REPLACE_BUCKET_NAME"

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
    bucket_key_enabled = true
  }
}
"""

AWS_TF_S3_LOGGING = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_s3_bucket" "sentinel_access_logs" {
  bucket = "REPLACE_ORG-access-logs-{region}"
}

resource "aws_s3_bucket_logging" "sentinel" {
  bucket = "REPLACE_TARGET_BUCKET"

  target_bucket = aws_s3_bucket.sentinel_access_logs.id
  target_prefix = "s3-access/"
}
"""

AWS_TF_SG_SSH = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}
# Replace sg-REPLACE with the open security group ID. Prefer SSM over open SSH.

resource "aws_security_group_rule" "deny_ssh_world_doc" {
  # REMOVE any inbound rule allowing 0.0.0.0/0 (or ::/0) to port 22.
  # Prefer:
  # - AWS Systems Manager Session Manager (no inbound 22)
  # - or restrict cidr_blocks to your corporate / VPN CIDR only
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks       = ["REPLACE_TRUSTED_CIDR/32"]
  security_group_id = "sg-REPLACE"
  description       = "SSH from trusted network only — Sentinel harden"
}
"""

AWS_TF_SG_RDP = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_security_group_rule" "deny_rdp_world_doc" {
  # REMOVE any inbound rule allowing 0.0.0.0/0 to port 3389.
  type              = "ingress"
  from_port         = 3389
  to_port           = 3389
  protocol          = "tcp"
  cidr_blocks       = ["REPLACE_TRUSTED_CIDR/32"]
  security_group_id = "sg-REPLACE"
  description       = "RDP from trusted network only — Sentinel harden"
}
"""

AWS_TF_IMDSV2 = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_ec2_instance_metadata_defaults" "sentinel" {
  http_tokens                 = "required"
  http_put_response_hop_limit = 2
  http_endpoint               = "enabled"
  instance_metadata_tags      = "disabled"
}

# For existing instances, also:
# aws ec2 modify-instance-metadata-options --instance-id i-REPLACE --http-tokens required
"""

AWS_TF_EBS_ENC = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_ebs_encryption_by_default" "sentinel" {
  enabled = true
}
"""

AWS_TF_CLOUDTRAIL = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_cloudtrail" "sentinel_org" {
  name                          = "sentinel-multi-region-trail"
  s3_bucket_name                = "REPLACE_CLOUDTRAIL_BUCKET"
  include_global_service_events = true
  is_multi_region_trail         = true
  enable_log_file_validation    = true
  is_organization_trail         = false

  event_selector {
    read_write_type           = "All"
    include_management_events = true
  }
}
"""

AWS_TF_CONFIG = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_config_configuration_recorder" "sentinel" {
  name     = "sentinel-recorder"
  role_arn = "arn:aws:iam::{account}:role/REPLACE_CONFIG_ROLE"

  recording_group {
    all_supported                 = true
    include_global_resource_types = true
  }
}

resource "aws_config_delivery_channel" "sentinel" {
  name           = "sentinel-delivery"
  s3_bucket_name = "REPLACE_CONFIG_BUCKET"
  depends_on     = [aws_config_configuration_recorder.sentinel]
}

resource "aws_config_configuration_recorder_status" "sentinel" {
  name       = aws_config_configuration_recorder.sentinel.name
  is_enabled = true
  depends_on = [aws_config_delivery_channel.sentinel]
}
"""

AWS_TF_GUARDDUTY = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_guardduty_detector" "sentinel" {
  enable = true
}
"""

AWS_TF_FLOW_LOGS = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_flow_log" "sentinel_vpc" {
  vpc_id               = "vpc-REPLACE"
  traffic_type         = "ALL"
  log_destination_type = "cloud-watch-logs"
  log_destination      = "arn:aws:logs:{region}:{account}:log-group:REPLACE_FLOW_LOGS"
  iam_role_arn         = "arn:aws:iam::{account}:role/REPLACE_FLOW_LOGS_ROLE"
}
"""

AWS_TF_KMS_ROTATION = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "aws_kms_key" "sentinel_example" {
  description             = "Sentinel-managed CMK with rotation"
  deletion_window_in_days = 30
  enable_key_rotation     = true
}

# For existing keys:
# aws kms enable-key-rotation --key-id REPLACE_KEY_ID
"""

AWS_TF_RDS = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# Encrypt + deletion protection on *new* instances. Existing DBs need snapshot→restore.
resource "aws_db_instance" "sentinel_example" {
  identifier                 = "REPLACE_DB_ID"
  engine                     = "postgres"
  instance_class             = "db.t3.micro"
  allocated_storage          = 20
  username                   = "REPLACE"
  password                   = "REPLACE_VIA_SECRETS_MANAGER"
  storage_encrypted          = true
  deletion_protection        = true
  backup_retention_period    = 7
  skip_final_snapshot        = false
  final_snapshot_identifier  = "REPLACE_DB_ID-final"
}
"""

AZ_TF_STORAGE_HTTPS = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "azurerm_storage_account" "sentinel_example" {
  name                     = "REPLACE_STORAGE"
  resource_group_name      = "REPLACE_RG"
  location                 = "{region}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  https_traffic_only_enabled = true
  min_tls_version            = "TLS1_2"
  allow_nested_items_to_be_public = false
}
"""

AZ_TF_STORAGE_PUBLIC = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "azurerm_storage_account" "sentinel_no_anon" {
  name                            = "REPLACE_STORAGE"
  resource_group_name             = "REPLACE_RG"
  location                        = "{region}"
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
  # Also set blob public access off at account:
  # shared_access_key_enabled etc. as required by org policy
}
"""

AZ_TF_NSG_SSH = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}
# Remove any NSG rule allowing Internet → 22. Prefer Azure Bastion / Just-In-Time.

resource "azurerm_network_security_rule" "ssh_trusted_only" {
  name                        = "ssh-trusted-only"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "22"
  source_address_prefix       = "REPLACE_TRUSTED_CIDR"
  destination_address_prefix  = "*"
  resource_group_name         = "REPLACE_RG"
  network_security_group_name = "REPLACE_NSG"
}
"""

AZ_TF_NSG_RDP = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "azurerm_network_security_rule" "rdp_trusted_only" {
  name                        = "rdp-trusted-only"
  priority                    = 110
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "3389"
  source_address_prefix       = "REPLACE_TRUSTED_CIDR"
  destination_address_prefix  = "*"
  resource_group_name         = "REPLACE_RG"
  network_security_group_name = "REPLACE_NSG"
}
"""

AZ_TF_KEYVAULT = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "azurerm_key_vault" "sentinel" {
  name                       = "REPLACE_KV_NAME"
  location                   = "{region}"
  resource_group_name        = "REPLACE_RG"
  tenant_id                  = "REPLACE_TENANT_ID"
  sku_name                   = "standard"
  soft_delete_retention_days = 90
  purge_protection_enabled   = true

  network_acls {
    default_action = "Deny"
    bypass         = "AzureServices"
    # ip_rules / virtual_network_subnet_ids as needed
  }
}
"""

AZ_TF_DEFENDER = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "azurerm_security_center_subscription_pricing" "vms" {
  tier          = "Standard"
  resource_type = "VirtualMachines"
}
resource "azurerm_security_center_subscription_pricing" "sql" {
  tier          = "Standard"
  resource_type = "SqlServers"
}
resource "azurerm_security_center_subscription_pricing" "storage" {
  tier          = "Standard"
  resource_type = "StorageAccounts"
}
resource "azurerm_security_center_subscription_pricing" "kv" {
  tier          = "Standard"
  resource_type = "KeyVaults"
}
"""

AZ_TF_MONITOR = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "azurerm_log_analytics_workspace" "sentinel" {
  name                = "sentinel-law"
  location            = "{region}"
  resource_group_name = "REPLACE_RG"
  sku                 = "PerGB2018"
  retention_in_days   = 365
}

resource "azurerm_monitor_diagnostic_setting" "activity" {
  name                       = "sentinel-activity-to-law"
  target_resource_id         = "/subscriptions/REPLACE_SUB_ID"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.sentinel.id

  enabled_log {
    category = "Administrative"
  }
  enabled_log {
    category = "Security"
  }
}
"""

AZ_TF_SQL_TDE = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "azurerm_mssql_database" "sentinel_example" {
  name           = "REPLACE_DB"
  server_id      = "REPLACE_SERVER_ID"
  collation      = "SQL_Latin1_General_CP1_CI_AS"
  max_size_gb    = 2
  sku_name       = "S0"
  # TDE is on by default for Azure SQL; enforce audit below in companion files
}
"""

AZ_TF_VM_DISK = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

resource "azurerm_virtual_machine_extension" "ade_example" {
  name                 = "AzureDiskEncryption"
  virtual_machine_id   = "REPLACE_VM_ID"
  publisher            = "Microsoft.Azure.Security"
  type                 = "AzureDiskEncryption"
  type_handler_version = "2.2"

  settings = jsonencode({
    EncryptionOperation    = "EnableEncryption"
    KeyVaultURL            = "https://REPLACE_KV.vault.azure.net/"
    KeyVaultResourceId     = "REPLACE_KV_RESOURCE_ID"
    KeyEncryptionKeyURL    = "https://REPLACE_KV.vault.azure.net/keys/REPLACE"
    KekVaultResourceId     = "REPLACE_KV_RESOURCE_ID"
    VolumeType             = "All"
  })
}
"""


# ── Perimeter / AppSec config fragments (nginx / headers) ─────────────────────

CONF_NGINX_HEADERS = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}
# Drop into server { } or include from /etc/nginx/conf.d/sentinel-headers.conf
# REVIEW before apply. dry_run kit — does not mutate your edge by itself.

# --- HTTPS redirect (use at http server block) ---
# server {
#   listen 80;
#   server_name REPLACE_HOSTNAME;
#   return 301 https://$host$request_uri;
# }

add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "DENY" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
add_header Content-Security-Policy "default-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'" always;

# Hide fingerprinting
server_tokens off;
# proxy_hide_header X-Powered-By;
"""

CONF_HSTS = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# nginx:
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

# Cloudflare / CDN: enable HTTP Strict Transport Security in TLS settings.
# AWS ALB + CloudFront: set response header policy with HSTS.
"""

CONF_CSP = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}
# Start report-only, then enforce after console is clean.

add_header Content-Security-Policy-Report-Only "default-src 'self'; img-src 'self' data: https:; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; report-uri /csp-report" always;

# Enforce (after tuning):
# add_header Content-Security-Policy "default-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'self'" always;
"""

CONF_CORS = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}
# NEVER combine Access-Control-Allow-Origin: * with Allow-Credentials: true

# nginx example — pin to known frontends only
# set $cors_origin "";
# if ($http_origin ~* ^(https://app\\.REPLACE_DOMAIN|https://admin\\.REPLACE_DOMAIN)$) {
#   set $cors_origin $http_origin;
# }
# add_header Access-Control-Allow-Origin $cors_origin always;
# add_header Access-Control-Allow-Credentials "true" always;
# add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
# add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;
# add_header Vary "Origin" always;

# Application (preferred): whitelist origins in API gateway / app config. No wildcards with credentials.
"""

CONF_COOKIE = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# Set-Cookie requirements for session tokens:
#   Secure; HttpOnly; SameSite=Lax  (or Strict for admin)
# Example (app / reverse-proxy):
#   Set-Cookie: session=...; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=3600

# nginx cannot mint secure app cookies alone — fix in application or auth service.
"""

CONF_XFO = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

add_header X-Frame-Options "DENY" always;
# Modern equivalent inside CSP:
# add_header Content-Security-Policy "frame-ancestors 'none'" always;
"""

CONF_XCTO = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

add_header X-Content-Type-Options "nosniff" always;
"""

CONF_REFERRER = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

add_header Referrer-Policy "strict-origin-when-cross-origin" always;
"""

CONF_SECURITY_TXT = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}
# Publish at: https://REPLACE_HOSTNAME/.well-known/security.txt

Contact: mailto:security@REPLACE_DOMAIN
Expires: 2027-12-31T23:59:00.000Z
Preferred-Languages: en
Canonical: https://REPLACE_HOSTNAME/.well-known/security.txt
Policy: https://REPLACE_HOSTNAME/security-policy
"""

CONF_TLS_REDIRECT = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# nginx HTTP → HTTPS
server {
  listen 80;
  listen [::]:80;
  server_name REPLACE_HOSTNAME;
  return 301 https://$host$request_uri;
}

# TLS server (pairs with certificate via ACME / ACM / Key Vault)
# server {
#   listen 443 ssl http2;
#   server_name REPLACE_HOSTNAME;
#   ssl_certificate     /etc/ssl/certs/REPLACE.fullchain.pem;
#   ssl_certificate_key /etc/ssl/private/REPLACE.key;
#   ssl_protocols TLSv1.2 TLSv1.3;
#   ssl_prefer_server_ciphers off;
# }
"""

CONF_API_LOCKDOWN = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# 1) Do not expose admin/actuator/swagger on the public edge without auth + IP allowlist.
# 2) API gateway / WAF rules (conceptual):
#    - Block or auth-gate: /admin, /actuator, /swagger, /openapi, /graphql (if unused)
#    - Rate-limit auth and admin routes
#    - Strip path probes for /.env, /.git, /wp-json/wp/v2/users

# nginx deny example for secrets:
  location ~ /\\\\.(env|git) {
  deny all;
  return 404;
}

location ~* /(actuator|swagger|openapi) {
  # allow only VPN / private CIDR
  allow REPLACE_TRUSTED_CIDR;
  deny all;
}
"""

CONF_XSS = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# Application defenses (do all):
# 1) Context-aware output encoding (HTML/attr/JS/URL)
# 2) CSP with script-src 'self' (avoid unsafe-inline long-term)
# 3) HttpOnly cookies; never reflect unsanitized input into HTML
# 4) Framework auto-escaping ON

add_header Content-Security-Policy "default-src 'self'; script-src 'self'; object-src 'none'; base-uri 'self'" always;
add_header X-Content-Type-Options "nosniff" always;
"""

CONF_SQLI = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# Application defenses (do all):
# 1) Parameterized queries / prepared statements ONLY — never string-concat SQL
# 2) ORM bind parameters; disable raw SQL from user input
# 3) Least-privilege DB accounts (no DDL from app tier)
# 4) WAF SQLi rule pack as defense-in-depth — not the only control
# 5) Remove detailed DB errors from client responses (generic 500 page)
"""

CONF_PATH_TRAV = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# 1) Never map user input directly to filesystem paths
# 2) Resolve path, enforce allowlist root, reject .. and absolute paths
# 3) Serve user content from object storage with generated keys, not path joins
# nginx: disable unintended aliases; do not pass raw $uri into file roots from query args
"""

CONF_JWT = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# JWT harden checklist:
# - alg: RS256/ES256 preferred; reject alg=none
# - short exp (minutes for access tokens); refresh rotation
# - no secrets/PII in payload claims meant for confidentiality
# - store tokens in memory or Secure+HttpOnly cookies — not URL query
# - validate iss/aud/exp/nbf on every request
# - rotate signing keys; revoke list for logout / compromise
"""

CONF_CSRF = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# 1) Anti-CSRF token synchronized with session for state-changing POST/PUT/DELETE
# 2) SameSite=Lax or Strict on session cookies
# 3) Prefer backend frameworks' built-in CSRF middleware
# 4) For APIs: require custom header (e.g. X-Requested-With) + CORS allowlist
"""

CONF_OPEN_REDIRECT = """\
# {check_id} — {name}
# Generated by Sentinel Stacks Remediation Engine {version}

# 1) Do not redirect to user-supplied absolute URLs
# 2) Allowlist relative paths only OR signed redirect tokens
# 3) Reject //evil.com and encoded bypasses
"""


# Generic runbook YAML template
YML_GENERIC = """\
# {check_id} — {name}
# Severity: {severity}
# Generated by Sentinel Stacks Remediation Engine {version}
# Human review required before implementation.

apiVersion: sentinel-stacks/v1
kind: HardeningRunbook
metadata:
  check_id: "{check_id}"
  title: "{title}"
  severity: "{severity}"
  category: "{category}"
  resource_id: "{resource_id}"
  region: "{region}"
  dry_run: true
  requires_approval: true
spec:
  summary: |
    {description}
  prechecks:
    - Confirm change window and rollback plan with owner of {resource_id}
    - Snapshot / backup affected resources where applicable
    - Verify least-privilege credentials for implementer
  steps:
{steps_block}
  validation:
    - Re-run originating Sentinel scanner with same target
    - Confirm this check_id no longer appears as failed
    - Record evidence for audit trail
  rollback: |
    Revert Terraform/state or console changes using change ticket.
    Keep prior config export before apply.
"""


def _steps_block(steps: list[str]) -> str:
    if not steps:
        steps = ["Follow CIS / vendor documentation for this control."]
    lines = []
    for i, s in enumerate(steps, 1):
        clean = str(s).replace("\n", " ").strip()
        lines.append(f"    - step: {i}\n      action: |\n        {clean}")
    return "\n".join(lines)


FIX_MAP: dict[str, dict] = {
    # ── AWS ──────────────────────────────────────────────────────────────────
    "AWS-001": _fix(
        "Root Account MFA Enabled", "IAM", "runbook", effort="low",
        yml=None,  # generic
    ),
    "AWS-002": _fix(
        "IAM Password Policy — Minimum Length >= 14", "IAM", "both",
        tf=AWS_TF_IAM_PASSWORD, effort="low",
    ),
    "AWS-003": _fix(
        "IAM Password Policy — Uppercase + Symbols Required", "IAM", "both",
        tf=AWS_TF_IAM_PASSWORD, effort="low",
    ),
    "AWS-004": _fix(
        "No IAM Users with Console Access and Active Access Keys", "IAM", "runbook",
        effort="medium",
    ),
    "AWS-005": _fix(
        "No Wildcard (*) IAM Policies on Critical Resources", "IAM", "runbook",
        effort="high",
    ),
    "AWS-006": _fix(
        "S3 Public Access Block — All Buckets", "S3", "both",
        tf=AWS_TF_S3_PUBLIC_BLOCK, effort="low",
    ),
    "AWS-007": _fix(
        "S3 Bucket Default Encryption Enabled", "S3", "both",
        tf=AWS_TF_S3_ENCRYPTION, effort="low",
    ),
    "AWS-008": _fix(
        "S3 Bucket Logging Enabled", "S3", "both",
        tf=AWS_TF_S3_LOGGING, effort="medium",
    ),
    "AWS-009": _fix(
        "No Security Groups with 0.0.0.0/0 to Port 22 (SSH)", "EC2/Security Groups", "both",
        tf=AWS_TF_SG_SSH, effort="medium",
    ),
    "AWS-010": _fix(
        "No Security Groups with 0.0.0.0/0 to Port 3389 (RDP)", "EC2/Security Groups", "both",
        tf=AWS_TF_SG_RDP, effort="medium",
    ),
    "AWS-011": _fix(
        "EC2 IMDSv2 Required (No IMDSv1)", "EC2", "both",
        tf=AWS_TF_IMDSV2, effort="medium",
    ),
    "AWS-012": _fix(
        "EBS Volumes Encrypted by Default", "EC2", "both",
        tf=AWS_TF_EBS_ENC, effort="low",
    ),
    "AWS-013": _fix(
        "CloudTrail Enabled in All Regions", "CloudTrail", "both",
        tf=AWS_TF_CLOUDTRAIL, effort="medium",
    ),
    "AWS-014": _fix(
        "AWS Config Enabled and Recording", "AWS Config", "both",
        tf=AWS_TF_CONFIG, effort="medium",
    ),
    "AWS-015": _fix(
        "Amazon GuardDuty Enabled", "GuardDuty", "both",
        tf=AWS_TF_GUARDDUTY, effort="low",
    ),
    "AWS-016": _fix(
        "VPC Flow Logs Enabled", "VPC", "both",
        tf=AWS_TF_FLOW_LOGS, effort="medium",
    ),
    "AWS-017": _fix(
        "KMS Customer-Managed Keys with Rotation", "KMS", "both",
        tf=AWS_TF_KMS_ROTATION, effort="medium",
    ),
    "AWS-018": _fix(
        "RDS Instances Have Storage Encryption and Deletion Protection", "RDS", "both",
        tf=AWS_TF_RDS, effort="high",
    ),
    # ── Azure ────────────────────────────────────────────────────────────────
    "AZ-001": _fix("Security Defaults or Conditional Access MFA", "Entra ID", "runbook", effort="medium"),
    "AZ-002": _fix("No Legacy Authentication Protocols Enabled", "Entra ID", "runbook", effort="medium"),
    "AZ-003": _fix("Guest User Access Reviewed and Restricted", "Entra ID", "runbook", effort="low"),
    "AZ-004": _fix(
        "Storage Accounts: Secure Transfer Required (HTTPS Only)", "Storage Accounts", "both",
        tf=AZ_TF_STORAGE_HTTPS, effort="low",
    ),
    "AZ-005": _fix(
        "Storage Accounts: No Public Anonymous Blob Access", "Storage Accounts", "both",
        tf=AZ_TF_STORAGE_PUBLIC, effort="low",
    ),
    "AZ-006": _fix("Storage Accounts: Blob Encryption with CMK", "Storage Accounts", "runbook", effort="high"),
    "AZ-007": _fix(
        "No NSG Rules Allowing Internet to Port 22 (SSH)", "Network Security Groups", "both",
        tf=AZ_TF_NSG_SSH, effort="medium",
    ),
    "AZ-008": _fix(
        "No NSG Rules Allowing Internet to Port 3389 (RDP)", "Network Security Groups", "both",
        tf=AZ_TF_NSG_RDP, effort="medium",
    ),
    "AZ-009": _fix(
        "Key Vault: Soft Delete and Purge Protection Enabled", "Key Vault", "both",
        tf=AZ_TF_KEYVAULT, effort="medium",
    ),
    "AZ-010": _fix(
        "Key Vault: Network Access Restricted", "Key Vault", "both",
        tf=AZ_TF_KEYVAULT, effort="medium",
    ),
    "AZ-011": _fix(
        "Defender for Cloud: Standard Tier", "Defender for Cloud", "both",
        tf=AZ_TF_DEFENDER, effort="low",
    ),
    "AZ-012": _fix(
        "Defender for Cloud: All Plans Enabled", "Defender for Cloud", "both",
        tf=AZ_TF_DEFENDER, effort="low",
    ),
    "AZ-013": _fix(
        "Activity Log Export to Log Analytics", "Monitoring", "both",
        tf=AZ_TF_MONITOR, effort="medium",
    ),
    "AZ-014": _fix(
        "Log Analytics Workspace Retention >= 365 Days", "Monitoring", "both",
        tf=AZ_TF_MONITOR, effort="low",
    ),
    "AZ-015": _fix(
        "Azure SQL: TDE Enabled", "Azure SQL", "both",
        tf=AZ_TF_SQL_TDE, effort="medium",
    ),
    "AZ-016": _fix("Azure SQL: Auditing Enabled", "Azure SQL", "runbook", effort="medium"),
    "AZ-017": _fix(
        "VM Disks Encrypted", "Virtual Machines", "both",
        tf=AZ_TF_VM_DISK, effort="high",
    ),
    "AZ-018": _fix("No Public IP on Sensitive Workloads", "Virtual Machines", "runbook", effort="high"),
    # ── Governance (stable catalog IDs) — deeper configs ─────────────────────
    "GOV-SSL": _fix(
        "TLS / HTTPS Enforcement", "Governance", "both",
        conf=CONF_TLS_REDIRECT, effort="medium",
    ),
    "GOV-HSTS": _fix(
        "HTTP Strict Transport Security (HSTS)", "Governance", "both",
        conf=CONF_HSTS, effort="low",
    ),
    "GOV-CSP": _fix(
        "Content Security Policy", "Governance", "both",
        conf=CONF_CSP, effort="medium",
    ),
    "GOV-CORS": _fix(
        "CORS Configuration", "Governance", "both",
        conf=CONF_CORS, effort="medium",
    ),
    "GOV-COOKIE": _fix(
        "Cookie Security Flags", "Governance", "both",
        conf=CONF_COOKIE, effort="low",
    ),
    "GOV-XFO": _fix(
        "Clickjacking Protection (X-Frame-Options)", "Governance", "both",
        conf=CONF_XFO, effort="low",
    ),
    "GOV-XCTO": _fix(
        "MIME Type Protection (X-Content-Type-Options)", "Governance", "both",
        conf=CONF_XCTO, effort="low",
    ),
    "GOV-SECURITY-TXT": _fix(
        "security.txt — Vulnerability Disclosure", "Governance", "both",
        conf=CONF_SECURITY_TXT, effort="low",
    ),
    "GOV-PRIVACY": _fix("Privacy Policy / Data Protection Notice", "Governance", "runbook", effort="low"),
    "GOV-SERVER-INFO": _fix(
        "Server Information Leakage", "Governance", "both",
        conf=CONF_NGINX_HEADERS, effort="low",
    ),
    "GOV-REFERRER": _fix(
        "Referrer Policy", "Governance", "both",
        conf=CONF_REFERRER, effort="low",
    ),
    "GOV-REDIRECT": _fix(
        "HTTP-to-HTTPS Redirect", "Governance", "both",
        conf=CONF_TLS_REDIRECT, effort="medium",
    ),

    # ── Perimeter AppSec — VULN (from scan_vuln_hunter titles) ────────────────
    "VULN-XSS": _fix("Reflected XSS", "AppSec", "both", conf=CONF_XSS, effort="high"),
    "VULN-SQLI": _fix("SQL Injection", "AppSec", "both", conf=CONF_SQLI, effort="high"),
    "VULN-PATH-TRAVERSAL": _fix("Path Traversal", "AppSec", "both", conf=CONF_PATH_TRAV, effort="high"),
    "VULN-CORS": _fix("CORS Misconfiguration", "AppSec", "both", conf=CONF_CORS, effort="medium"),
    "VULN-HSTS": _fix("Missing HSTS", "AppSec", "both", conf=CONF_HSTS, effort="low"),
    "VULN-CSP": _fix("Missing CSP", "AppSec", "both", conf=CONF_CSP, effort="medium"),
    "VULN-XFO": _fix("Missing X-Frame-Options", "AppSec", "both", conf=CONF_XFO, effort="low"),
    "VULN-XCTO": _fix("Missing X-Content-Type-Options", "AppSec", "both", conf=CONF_XCTO, effort="low"),
    "VULN-REFERRER": _fix("Missing Referrer-Policy", "AppSec", "both", conf=CONF_REFERRER, effort="low"),
    "VULN-PERMISSIONS": _fix("Missing Permissions-Policy", "AppSec", "both", conf=CONF_NGINX_HEADERS, effort="low"),
    "VULN-MIXED-CONTENT": _fix("Mixed Content", "AppSec", "both", conf=CONF_TLS_REDIRECT, effort="medium"),
    "VULN-OPEN-REDIRECT": _fix("Open Redirect", "AppSec", "both", conf=CONF_OPEN_REDIRECT, effort="medium"),
    "VULN-DEBUG-ENDPOINT": _fix("Debug/Sensitive Endpoint Exposed", "AppSec", "both", conf=CONF_API_LOCKDOWN, effort="medium"),
    "VULN-LOG-EXPOSURE": _fix("Log File Potentially Exposed", "AppSec", "both", conf=CONF_API_LOCKDOWN, effort="medium"),

    # ── Perimeter Identity — IDENT (from scan_identity_guard titles) ──────────
    "IDENT-SESSION-COOKIE": _fix("Insecure Session Cookie", "Identity", "both", conf=CONF_COOKIE, effort="medium"),
    "IDENT-JWT": _fix("JWT Weakness", "Identity", "both", conf=CONF_JWT, effort="high"),
    "IDENT-BASIC-AUTH-HTTP": _fix("Basic Auth without HTTPS", "Identity", "both", conf=CONF_TLS_REDIRECT, effort="high"),
    "IDENT-TOKEN-IN-URL": _fix("Session Token Leaked in URL", "Identity", "both", conf=CONF_JWT, effort="high"),
    "IDENT-CORS-CREDS": _fix("CORS Credentials Misconfiguration", "Identity", "both", conf=CONF_CORS, effort="medium"),
    "IDENT-CSRF": _fix("Login Form without CSRF Protection", "Identity", "both", conf=CONF_CSRF, effort="medium"),
    "IDENT-LOGIN-HTTP": _fix("Login over Plain HTTP", "Identity", "both", conf=CONF_TLS_REDIRECT, effort="high"),
    "IDENT-BEARER-EXPOSED": _fix("Bearer Token Exposed in Body", "Identity", "both", conf=CONF_JWT, effort="high"),
    "IDENT-CACHE-CONTROL": _fix("Authenticated Page Missing Cache-Control", "Identity", "runbook", effort="low"),
    "IDENT-OIDC-HTTP": _fix("OIDC Issuer uses HTTP", "Identity", "both", conf=CONF_TLS_REDIRECT, effort="high"),
    "IDENT-OIDC-IMPLICIT": _fix("OIDC Implicit Flow Enabled", "Identity", "runbook", effort="medium"),
    "IDENT-OIDC-ROPC": _fix("OIDC Resource Owner Password Grant", "Identity", "runbook", effort="medium"),

    # ── Perimeter API — FIND (from scan_public_url_api_scout titles) ───────────
    "FIND-API-USER": _fix("API User Endpoint Exposed", "API Security", "both", conf=CONF_API_LOCKDOWN, effort="medium"),
    "FIND-API-ADMIN": _fix("API Admin Endpoint Exposed", "API Security", "both", conf=CONF_API_LOCKDOWN, effort="high"),
    "FIND-GRAPHQL": _fix("GraphQL Endpoint Exposed", "API Security", "both", conf=CONF_API_LOCKDOWN, effort="medium"),
    "FIND-SWAGGER": _fix("Swagger/OpenAPI Spec Exposed", "API Security", "both", conf=CONF_API_LOCKDOWN, effort="medium"),
    "FIND-OPENAPI": _fix("OpenAPI Spec Exposed", "API Security", "both", conf=CONF_API_LOCKDOWN, effort="medium"),
    "FIND-ACTUATOR": _fix("Spring Boot Actuator Exposed", "API Security", "both", conf=CONF_API_LOCKDOWN, effort="high"),
    "FIND-WP-USERS": _fix("WordPress User Enumeration Endpoint", "API Security", "both", conf=CONF_API_LOCKDOWN, effort="medium"),
    "FIND-ENV": _fix("Environment File Exposed", "API Security", "both", conf=CONF_API_LOCKDOWN, effort="high"),
    "FIND-ADMIN-PANEL": _fix("Admin Panel Publicly Accessible", "API Security", "both", conf=CONF_API_LOCKDOWN, effort="high"),

    # ── Data / Network generic (title-map warmers for data/network scouts) ────
    "DATA-SECRET-EXPOSURE": _fix("Secret or Credential Exposure", "Data Security", "both", conf=CONF_API_LOCKDOWN, effort="high"),
    "DATA-PII-EXPOSURE": _fix("PII Exposure", "Data Security", "runbook", effort="high"),
    "NET-OPEN-PORT": _fix("Sensitive Port Exposure", "Network", "runbook", effort="medium"),
    "NET-TLS-WEAK": _fix("Weak TLS Configuration", "Network", "both", conf=CONF_TLS_REDIRECT, effort="medium"),
}

# Title fragment → stable control id (when runtime emits GOV-001 / VULN-003 / FIND-001)
PERIM_TITLE_MAP = [
    # --- MOST SPECIFIC FIRST (Perimeter scanners emit sequential FIND/VULN/IDENT ids) ---
    # AppSec / VULN
    (re.compile(r"Reflected XSS|Cross-Site Scripting|\bXSS\b", re.I), "VULN-XSS"),
    (re.compile(r"SQL Injection|SQLi|database error exposed", re.I), "VULN-SQLI"),
    (re.compile(r"Path Traversal|directory traversal", re.I), "VULN-PATH-TRAVERSAL"),
    (re.compile(r"Permissions-Policy|Missing Permissions", re.I), "VULN-PERMISSIONS"),
    (re.compile(r"Open Redirect", re.I), "VULN-OPEN-REDIRECT"),
    (re.compile(r"Debug/.?sensitive endpoint|Debug endpoint", re.I), "VULN-DEBUG-ENDPOINT"),
    (re.compile(r"Log file potentially exposed", re.I), "VULN-LOG-EXPOSURE"),
    (re.compile(r"Mixed content", re.I), "VULN-MIXED-CONTENT"),
    (re.compile(r"CORS Misconfiguration|credentials with wildcard", re.I), "VULN-CORS"),
    # Identity
    (re.compile(r"Insecure session cookie", re.I), "IDENT-SESSION-COOKIE"),
    (re.compile(r"Session token leaked in URL", re.I), "IDENT-TOKEN-IN-URL"),
    (re.compile(r"Basic Authentication offered without HTTPS", re.I), "IDENT-BASIC-AUTH-HTTP"),
    (re.compile(r"Login form without CSRF", re.I), "IDENT-CSRF"),
    (re.compile(r"Login form submits credentials over plain HTTP", re.I), "IDENT-LOGIN-HTTP"),
    (re.compile(r"Bearer token exposed in response body", re.I), "IDENT-BEARER-EXPOSED"),
    (re.compile(r"OIDC issuer uses HTTP", re.I), "IDENT-OIDC-HTTP"),
    (re.compile(r"implicit flow", re.I), "IDENT-OIDC-IMPLICIT"),
    (re.compile(r"Resource Owner Password", re.I), "IDENT-OIDC-ROPC"),
    (re.compile(r"Cache-Control", re.I), "IDENT-CACHE-CONTROL"),
    (re.compile(r"\bJWT\b", re.I), "IDENT-JWT"),
    (re.compile(r"CORS: Allow-Credentials|CORS: Credentials allowed", re.I), "IDENT-CORS-CREDS"),
    # API FIND
    (re.compile(r"API user endpoint exposed", re.I), "FIND-API-USER"),
    (re.compile(r"API admin endpoint exposed", re.I), "FIND-API-ADMIN"),
    (re.compile(r"GraphQL endpoint exposed", re.I), "FIND-GRAPHQL"),
    (re.compile(r"Swagger/OpenAPI", re.I), "FIND-SWAGGER"),
    (re.compile(r"OpenAPI spec exposed", re.I), "FIND-OPENAPI"),
    (re.compile(r"Spring Boot Actuator", re.I), "FIND-ACTUATOR"),
    (re.compile(r"WordPress user enumeration", re.I), "FIND-WP-USERS"),
    (re.compile(r"Environment file exposed", re.I), "FIND-ENV"),
    (re.compile(r"Admin panel publicly accessible", re.I), "FIND-ADMIN-PANEL"),
    # Data / Network
    (re.compile(r"\bPII\b|social security|credit card", re.I), "DATA-PII-EXPOSURE"),
    (re.compile(r"secret|credential|api[_-]?key|aws_access|\.env", re.I), "DATA-SECRET-EXPOSURE"),
    (re.compile(r"open port|port 22|port 3389|exposed service", re.I), "NET-OPEN-PORT"),
    (re.compile(r"Weak TLS|TLS 1\.0|SSLv3", re.I), "NET-TLS-WEAK"),
    # Governance stable names (last among header overlaps)
    (re.compile(r"HTTPS Enforcement|TLS certificate|\bTLS\b.*Enforcement", re.I), "GOV-SSL"),
    (re.compile(r"\bHSTS\b|Strict-Transport|Missing Strict-Transport", re.I), "GOV-HSTS"),
    (re.compile(r"Content.Security.Policy|\bCSP\b|Missing Content-Security", re.I), "GOV-CSP"),
    (re.compile(r"\bCORS\b", re.I), "GOV-CORS"),
    (re.compile(r"Cookie Security|Set-Cookie|Missing .*[Cc]ookie", re.I), "GOV-COOKIE"),
    (re.compile(r"X-Frame|Clickjack|frame-ancestors", re.I), "GOV-XFO"),
    (re.compile(r"X-Content-Type|nosniff|MIME Type", re.I), "GOV-XCTO"),
    (re.compile(r"security\.txt", re.I), "GOV-SECURITY-TXT"),
    (re.compile(r"Privacy Policy", re.I), "GOV-PRIVACY"),
    (re.compile(r"Server Information|X-Powered-By|server_tokens", re.I), "GOV-SERVER-INFO"),
    (re.compile(r"Referrer-Policy|Referrer Policy|Missing Referrer", re.I), "GOV-REFERRER"),
    (re.compile(r"HTTP-to-HTTPS|HTTPS Redirect", re.I), "GOV-REDIRECT"),
]

# Back-compat alias used by older comments
GOV_TITLE_MAP = PERIM_TITLE_MAP


# ═══════════════════════ Helpers ══════════════════════════════════════════════

def _ts() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _now() -> datetime.datetime:
    return datetime.datetime.now(datetime.timezone.utc)


def _sev_rank(sev: str) -> int:
    return SEV_ORDER.get(str(sev).lower(), 0)


def _safe_name(s: str) -> str:
    s = re.sub(r"[^\w.\-]+", "_", s.strip())
    return s[:80] or "item"


def _empty_report(target: str, status: str, error: str | None) -> dict:
    return {
        "tool_id": TOOL_ID,
        "version": VERSION,
        "execution": {
            "timestamp": _ts(),
            "duration_seconds": 0.0,
            "target": target,
            "status": status,
            "error": error,
            "mode": "dry_run",
        },
        "summary": {
            "total_findings": 0,
            "critical": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
            "info": 0,
            "kits_generated": 0,
            "fixes_mapped": 0,
            "fixes_unmapped": 0,
            "artifacts_written": 0,
        },
        "findings": [],
        "metadata": {
            "domain": DOMAIN,
            "subdomain": SUBDOMAIN,
            "sentinel": SENTINEL,
            "tier": TIER,
            "tags": TAGS,
            "llm_summary": f"Remediation engine failed for {target}: {error}." if error else "No run.",
            "kit_path": None,
            "dry_run": True,
        },
    }


def _load_scan_report(params: dict) -> tuple[dict | None, str, str | None]:
    """Return (report_dict, target_label, error)."""
    if params.get("scan_report") and isinstance(params["scan_report"], dict):
        rep = params["scan_report"]
        return rep, str(rep.get("execution", {}).get("target") or params.get("target") or "inline"), None

    if params.get("findings") and isinstance(params["findings"], list):
        synthetic = {
            "tool_id": "inline_findings",
            "version": "0.0.0",
            "execution": {"target": params.get("target", "inline"), "status": "success"},
            "summary": {},
            "findings": params["findings"],
            "metadata": {},
        }
        return synthetic, str(params.get("target") or "inline"), None

    target = str(params.get("target") or params.get("input_file") or "").strip()
    if not target:
        return None, "", "missing target (path to scanner JSON, or scan_report/findings)"

    path = target
    if path.startswith("file://"):
        path = path[7:]
    # Windows-friendly strip only click scheme
    path = os.path.expanduser(path)
    if not os.path.isfile(path):
        return None, target, f"scan report file not found: {path}"
    try:
        # utf-8-sig strips PowerShell Set-Content BOM if present
        with open(path, "r", encoding="utf-8-sig") as f:
            rep = json.load(f)
    except Exception as e:
        return None, target, f"invalid JSON: {e}"
    if not isinstance(rep, dict):
        return None, target, "scan report root must be a JSON object"
    return rep, str(rep.get("execution", {}).get("target") or path), None


def _resolve_check_id(finding: dict) -> str:
    """Map finding → stable FIX_MAP key (AWS/AZ/GOV/VULN/FIND/IDENT/...)."""
    ev = finding.get("evidence") or {}
    if isinstance(ev, dict) and ev.get("check_id"):
        cid = str(ev["check_id"]).strip()
        if cid in FIX_MAP:
            return cid
        # still try title map if check_id unknown
    fid = str(finding.get("id") or "").strip()
    if fid in FIX_MAP:
        return fid

    title = str(finding.get("title") or "")
    desc = str(finding.get("description") or "")
    blob = f"{title} {desc}"

    # Sequential perimeter IDs (GOV-001, VULN-003, FIND-002, IDENT-010) → title map
    if re.match(r"^(GOV|VULN|FIND|IDENT|NET|DATA)-\d{3}$", fid, re.I) or not fid:
        for rx, gid in PERIM_TITLE_MAP:
            if rx.search(blob):
                return gid

    # Always try title map as secondary for any unmapped id
    if fid not in FIX_MAP:
        for rx, gid in PERIM_TITLE_MAP:
            if rx.search(blob):
                return gid

    # AWS/AZ sequential
    m = re.match(r"^(AWS|AZ)-(\d{3})$", fid, re.I)
    if m:
        return f"{m.group(1).upper()}-{m.group(2)}"
    return fid


def _threshold_ok(sev: str, threshold: str) -> bool:
    return _sev_rank(sev) >= _sev_rank(threshold) and sev.lower() in ACTIONABLE


def _render(template: str, ctx: dict) -> str:
    out = template
    for k, v in ctx.items():
        out = out.replace("{" + k + "}", str(v))
    return out


def _default_runbook_steps(finding: dict, check_id: str) -> list[str]:
    rem = finding.get("remediation") or {}
    steps = rem.get("steps") if isinstance(rem, dict) else None
    if steps:
        return list(steps)
    return [
        f"Open control {check_id}: {finding.get('title')}",
        finding.get("description") or "Apply CIS / vendor harden guidance.",
        "Re-scan with the originating Sentinel module to verify.",
    ]


def _zip_dir(src_dir: Path, zip_path: Path) -> None:
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in sorted(src_dir.rglob("*")):
            if p.is_file():
                zf.write(p, arcname=str(p.relative_to(src_dir)))


# ═══════════════════════ Main ═════════════════════════════════════════════════

def run(params: dict) -> dict:
    started = _now()
    params = params or {}

    dry_run = params.get("dry_run", True)
    if dry_run is False:
        # Never auto-apply cloud changes in v1.0.0 — always kit-only.
        # apply mode is reserved for a future controlled actuation module.
        dry_run = True

    severity_threshold = str(params.get("severity_threshold") or "info").lower()
    if severity_threshold not in SEV_ORDER:
        severity_threshold = "info"

    max_runtime = int(params.get("max_runtime_seconds") or 300)
    output_dir = Path(str(params.get("output_dir") or "hardening_kits")).expanduser()

    report, target_label, err = _load_scan_report(params)
    if err:
        return _empty_report(target_label or "", "failed", err)

    findings_in = report.get("findings") or []
    if not isinstance(findings_in, list):
        return _empty_report(target_label, "failed", "scan report findings must be a list")

    source_tool = report.get("tool_id") or "unknown_scanner"
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    kit_name = f"kit_{_safe_name(source_tool)}_{stamp}"
    kit_root = output_dir / kit_name
    tf_dir = kit_root / "terraform"
    yml_dir = kit_root / "runbooks"
    conf_dir = kit_root / "configs"
    kit_root.mkdir(parents=True, exist_ok=True)
    tf_dir.mkdir(exist_ok=True)
    yml_dir.mkdir(exist_ok=True)
    conf_dir.mkdir(exist_ok=True)

    mapped = 0
    unmapped = 0
    artifacts = 0
    out_findings = []
    fid = 0
    pick_log = []

    for f in findings_in:
        if not isinstance(f, dict):
            continue
        sev = str(f.get("severity") or "info").lower()
        # Skip Passed Info checks from auditors
        if sev == "info":
            title = str(f.get("title") or "")
            if "PASSED" in title.upper() or (f.get("evidence") or {}).get("passed") is True:
                continue
        if not _threshold_ok(sev, severity_threshold):
            continue

        check_id = _resolve_check_id(f)
        fix = FIX_MAP.get(check_id)
        resource = f.get("resource") or {}
        resource_id = str(resource.get("id") or target_label or "unknown")
        region = str(resource.get("region") or params.get("regions", ["us-east-1"])[0] if isinstance(params.get("regions"), list) else "us-east-1")
        account = str(resource.get("account") or resource.get("id") or "REPLACE_ACCOUNT")

        ctx = {
            "check_id": check_id,
            "name": (fix or {}).get("name") or f.get("title") or check_id,
            "title": f.get("title") or check_id,
            "severity": sev,
            "category": (fix or {}).get("category") or (f.get("evidence") or {}).get("category") or "general",
            "resource_id": resource_id,
            "region": region,
            "account": account,
            "description": f.get("description") or "",
            "version": VERSION,
            "steps_block": _steps_block(_default_runbook_steps(f, check_id)),
        }

        written = []
        needs_review = False

        if fix:
            mapped += 1
            artifact = fix.get("artifact") or "runbook"
            # Terraform
            if artifact in ("terraform", "both") and fix.get("tf"):
                tf_body = _render(fix["tf"], ctx)
                tf_path = tf_dir / f"{_safe_name(check_id)}.tf"
                tf_path.write_text(tf_body, encoding="utf-8")
                written.append(str(tf_path.relative_to(kit_root)))
                artifacts += 1
            # Perimeter / edge config fragments (nginx, headers, security.txt, etc.)
            if fix.get("conf"):
                conf_body = _render(fix["conf"], ctx)
                # .conf for nginx-style; .txt for security.txt content
                ext = ".txt" if "SECURITY-TXT" in check_id.upper() else ".conf"
                conf_path = conf_dir / f"{_safe_name(check_id)}{ext}"
                conf_path.write_text(conf_body, encoding="utf-8")
                written.append(str(conf_path.relative_to(kit_root)))
                artifacts += 1
            # Runbook YAML
            if artifact in ("runbook", "both", "config") or not written:
                yml_body = _render(YML_GENERIC, ctx)
                yml_path = yml_dir / f"{_safe_name(check_id)}.yml"
                yml_path.write_text(yml_body, encoding="utf-8")
                written.append(str(yml_path.relative_to(kit_root)))
                artifacts += 1
            pick_log.append({"check_id": check_id, "status": "mapped", "files": written})
        else:
            unmapped += 1
            needs_review = True
            # Heuristic artifact: runbook from embedded remediation.steps
            yml_body = _render(YML_GENERIC, ctx)
            yml_path = yml_dir / f"{_safe_name(check_id or f.get('id') or 'UNMAPPED')}_UNMAPPED.yml"
            yml_path.write_text(yml_body, encoding="utf-8")
            written.append(str(yml_path.relative_to(kit_root)))
            artifacts += 1
            pick_log.append({"check_id": check_id, "status": "unmapped_runbook", "files": written})

        fid += 1
        out_findings.append({
            "id": f"REM-{fid:03d}",
            "title": f"Hardening artifact generated for {check_id}" + (" (UNMAPPED — review)" if needs_review else ""),
            "severity": sev if not needs_review else ("medium" if sev == "info" else sev),
            "confidence": "high" if fix else "low",
            "resource": {
                "type": "hardening_artifact",
                "id": check_id,
                "region": region,
            },
            "description": (
                f"Created kit files for source finding '{f.get('id')}' "
                f"({f.get('title')}). Mapped={bool(fix)}. dry_run={dry_run}."
            ),
            "evidence": {
                "source_finding_id": f.get("id"),
                "source_tool_id": source_tool,
                "check_id": check_id,
                "mapped": bool(fix),
                "files": written,
                "fix_name": (fix or {}).get("name"),
            },
            "remediation": {
                "steps": [
                    f"Open kit files: {', '.join(written)}",
                    "Replace all REPLACE_* placeholders with real resource IDs.",
                    "Review in change window; apply via Terraform/console only after approval.",
                    "Re-run originating scanner to verify the control passes.",
                ],
                "effort": (fix or {}).get("effort") or "medium",
                "tier": 2,
                "reversible": True,
                "requires_approval": True,
            },
            "compliance": f.get("compliance") or [],
            "notes": "UNMAPPED — LLM or human should extend FIX_MAP" if needs_review else "",
        })

        # Respect max runtime (soft)
        if (_now() - started).total_seconds() > max_runtime:
            break

    # Manifest + README
    manifest = {
        "kit_name": kit_name,
        "generated_at": _ts(),
        "engine": {"tool_id": TOOL_ID, "version": VERSION},
        "source": {
            "tool_id": source_tool,
            "target": target_label,
            "risk_score": (report.get("summary") or {}).get("risk_score"),
        },
        "dry_run": dry_run,
        "severity_threshold": severity_threshold,
        "stats": {
            "input_findings": len(findings_in),
            "actionable_processed": mapped + unmapped,
            "mapped": mapped,
            "unmapped": unmapped,
            "artifacts": artifacts,
        },
        "items": pick_log,
        "warning": (
            "This kit does NOT apply changes. Human approval required. "
            "Replace REPLACE_* placeholders before terraform apply."
        ),
    }
    (kit_root / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    artifacts += 1

    readme = f"""# Sentinel Stacks — Hardening Kit

Generated: {manifest['generated_at']}
Source scanner: `{source_tool}`
Source target: `{target_label}`
Engine: `{TOOL_ID}` v{VERSION}

## What this is
Template fragments (Terraform + YAML runbooks) derived from scanner findings.
**The Kit is the Map. You are the Guide.** Nothing auto-applies to cloud.

## Layout
- `terraform/` — `.tf` blueprints (placeholders: REPLACE_*)
- `configs/` — nginx/header/API lockdown fragments
- `runbooks/` — step-by-step YAML per control
- `manifest.json` — machine index of generated items

## Stats
- Mapped controls: {mapped}
- Unmapped (review) controls: {unmapped}
- Artifacts: {artifacts}

## How to use
1. Review `manifest.json`
2. Edit placeholders in each file
3. Apply in a change window (Terraform plan → apply) **only after approval**
4. Re-run the originating Sentinel scanner
5. Archive this kit with ticket evidence

## dry_run
This engine runs with dry_run=true. It never calls AWS/Azure APIs to mutate state.
"""
    (kit_root / "README.md").write_text(readme, encoding="utf-8")
    artifacts += 1

    zip_path = output_dir / f"{kit_name}.zip"
    _zip_dir(kit_root, zip_path)

    # summary counts from out_findings
    crit = sum(1 for x in out_findings if x["severity"] == "critical")
    high = sum(1 for x in out_findings if x["severity"] == "high")
    med = sum(1 for x in out_findings if x["severity"] == "medium")
    low = sum(1 for x in out_findings if x["severity"] == "low")
    info = sum(1 for x in out_findings if x["severity"] == "info")
    total = len(out_findings)
    duration = (_now() - started).total_seconds()

    if total == 0:
        status = "success"
        verdict = "No actionable findings at the requested severity threshold — empty kit shell created."
    elif unmapped and not mapped:
        status = "partial"
        verdict = f"Generated unmapped runbooks only ({unmapped}). Extend FIX_MAP or review manually."
    elif unmapped:
        status = "partial"
        verdict = f"Kit ready: {mapped} mapped, {unmapped} unmapped require human/LLM review."
    else:
        status = "success"
        verdict = f"Kit ready: {mapped} controls fully mapped to templates."

    llm = (
        f"Remediation Engine packaged hardening kit '{kit_name}' from '{source_tool}' "
        f"target '{target_label}'. Processed {mapped + unmapped} actionable findings "
        f"({mapped} mapped, {unmapped} unmapped). Wrote {artifacts} artifacts. "
        f"ZIP: {zip_path}. dry_run=True (no cloud mutation). {verdict}"
    )

    return {
        "tool_id": TOOL_ID,
        "version": VERSION,
        "execution": {
            "timestamp": _ts(),
            "duration_seconds": round(duration, 2),
            "target": target_label,
            "status": status,
            "error": None,
            "mode": "dry_run",
        },
        "summary": {
            "total_findings": total,
            "critical": crit,
            "high": high,
            "medium": med,
            "low": low,
            "info": info,
            "kits_generated": 1,
            "fixes_mapped": mapped,
            "fixes_unmapped": unmapped,
            "artifacts_written": artifacts,
        },
        "findings": out_findings,
        "metadata": {
            "domain": DOMAIN,
            "subdomain": SUBDOMAIN,
            "sentinel": SENTINEL,
            "tier": TIER,
            "tags": TAGS,
            "llm_summary": llm,
            "kit_path": str(zip_path),
            "kit_dir": str(kit_root),
            "dry_run": True,
            "source_tool_id": source_tool,
            "fix_map_size": len(FIX_MAP),
        },
    }


def remediate(input_path: str, output_dir: str = "hardening_kits") -> dict:
    return run({
        "target": input_path,
        "output_dir": output_dir,
        "dry_run": True,
        "severity_threshold": "info",
    })


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(
            "Usage:\n"
            "  python ai_remediation_engine.py <scan_results.json> [output_dir]\n"
            "Example:\n"
            "  python ai_remediation_engine.py test-results-aws-vulnerable.json hardening_kits\n\n"
            "TOOL_STANDARDS: remediate_findings_hardening_kit (Tier 2, dry_run default).\n"
            "Consumes scanner JSON only — never mutates cloud.",
            file=sys.stderr,
        )
        sys.exit(0 if args and args[0] in ("-h", "--help") else 2)
    inp = args[0]
    out = args[1] if len(args) > 1 else "hardening_kits"
    result = run({"target": inp, "output_dir": out, "dry_run": True})
    print(json.dumps(result, indent=2))
