# change_assurance/capabilities/bootstrap.py
# Least-privilege BOOTSTRAP / CAPABILITY PROVISIONING artifacts.
# Never executable by the remediation role. Never auto-applied.

from __future__ import annotations

import json
from typing import Any

from change_assurance.capabilities.probe import expand_resource
from change_assurance.capabilities.types import (
    BOOTSTRAP_PENDING_ADMIN,
    CapabilitySpec,
    VERSION,
)


def render_inline_policy_document(
    spec: CapabilitySpec,
    *,
    account_id: str,
    region: str,
) -> dict[str, Any]:
    """Build least-privilege inline policy JSON for the remediation role."""
    statements: list[dict[str, Any]] = []
    # Group non-SLR actions
    service_actions = [
        p for p in spec.permissions if not p.action.startswith("iam:")
    ]
    iam_actions = [p for p in spec.permissions if p.action.startswith("iam:")]

    if service_actions:
        actions = [p.action for p in service_actions]
        # Prefer resource-scoped when all share same expanded resource
        resources = {
            expand_resource(p.resource, account_id=account_id, region=region)
            for p in service_actions
            if p.resource
        }
        resources.discard(None)
        stmt: dict[str, Any] = {
            "Sid": f"Manage{spec.service.title().replace('-', '')}Remediation",
            "Effect": "Allow",
            "Action": actions,
        }
        if len(resources) == 1:
            stmt["Resource"] = next(iter(resources))
        else:
            stmt["Resource"] = "*"
            stmt["Condition"] = {"StringEquals": {"aws:RequestedRegion": region}}
        statements.append(stmt)

    for p in iam_actions:
        stmt = {
            "Sid": p.action.split(":")[-1][:64],
            "Effect": "Allow",
            "Action": p.action,
            "Resource": expand_resource(p.resource, account_id=account_id, region=region)
            or "*",
        }
        if p.condition:
            stmt["Condition"] = p.condition
        statements.append(stmt)

    return {"Version": "2012-10-17", "Statement": statements}


def render_bootstrap_terraform(
    spec: CapabilitySpec,
    *,
    account_id: str,
    region: str,
    role_name: str,
    finding_id: str | None = None,
) -> str:
    """
    Terraform for BOOTSTRAP / CAPABILITY PROVISIONING only.
    Must not be applied by SentinelStacksRemediationRole (self-escalation forbidden).
    """
    doc = render_inline_policy_document(spec, account_id=account_id, region=region)
    doc_json = json.dumps(doc, indent=2)
    ctrl = finding_id or (spec.control_ids[0] if spec.control_ids else spec.capability_id)
    return f'''# BOOTSTRAP / CAPABILITY PROVISIONING — NOT ordinary security remediation
# Capability: {spec.capability_id}
# Control hint: {ctrl}
# Service: {spec.service}
# Generated by Sentinel Stacks capability bootstrap {VERSION}
#
# PURPOSE: Install least-privilege execution permissions on the remediation role
# so ordinary finding remediations (e.g. enabling GuardDuty) can later execute.
#
# This is NOT the GuardDuty/Config/Access Analyzer security change itself.
# After this bootstrap is applied and independently verified, ordinary remediation
# returns to the control-specific artifact only (no permanent IAM+control bundling).
#
# SECURITY:
# - Self-escalation forbidden: {role_name} MUST NOT apply this artifact
# - Scanner/planner MUST NOT apply this artifact
# - Requires explicitly authorized administrator bootstrap path
# - No wildcards (no iam:*, no {spec.service}:*)
# - dry_run / no auto-apply

resource "aws_iam_role_policy" "sentinel_capability_{spec.service.replace('-', '_')}" {{
  name = "{spec.inline_policy_name}"
  role = "{role_name}"

  policy = <<EOF
{doc_json}
EOF
}}
'''


def build_bootstrap_package(
    spec: CapabilitySpec,
    *,
    account_id: str,
    region: str,
    role_name: str,
    finding_id: str | None = None,
    missing_permissions: list[str] | None = None,
    identities: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Prepare bootstrap artifact metadata + Terraform (no AWS writes)."""
    tf = render_bootstrap_terraform(
        spec,
        account_id=account_id,
        region=region,
        role_name=role_name,
        finding_id=finding_id,
    )
    rel = f"bootstrap/capabilities/{spec.capability_id}.tf"
    from change_assurance.capabilities.types import IDENTITY_BOOTSTRAP_PROVISIONER

    idents = identities or {}
    bootstrap_meta = idents.get(IDENTITY_BOOTSTRAP_PROVISIONER) or {}

    return {
        "version": VERSION,
        "kind": "BOOTSTRAP_CAPABILITY_PROVISIONING",
        "label": "BOOTSTRAP / CAPABILITY PROVISIONING",
        "capability_id": spec.capability_id,
        "finding_id_hint": finding_id,
        "service": spec.service,
        "inline_policy_name": spec.inline_policy_name,
        "role_name": role_name,
        "terraform": tf,
        "terraform_relpath": rel,
        "policy_document": render_inline_policy_document(
            spec, account_id=account_id, region=region
        ),
        "missing_permissions": list(missing_permissions or []),
        "authorization_status": BOOTSTRAP_PENDING_ADMIN,
        "executable_by_remediation_role": False,
        "executable_by_scanner": False,
        "requires_admin_bootstrap": True,
        "bootstrap_path": bootstrap_meta,
        "self_escalation_forbidden": True,
        "aws_modified": False,
        "auto_applied": False,
        "ordinary_remediation_note": (
            "After capability READY, ordinary remediation is the control artifact only "
            f"(e.g. terraform/{finding_id or 'CONTROL'}.tf) — not this bootstrap policy."
        ),
    }
