# BOOTSTRAP / CAPABILITY PROVISIONING — NOT ordinary security remediation
# Capability: aws_guardduty_detector_enable
# Control hint: CLOUD-LOG-003
# Service: guardduty
# Generated by Sentinel Stacks capability bootstrap 0.1.0-capability
#
# PURPOSE: Install least-privilege execution permissions on the remediation role
# so ordinary finding remediations (e.g. enabling GuardDuty) can later execute.
#
# This is NOT the GuardDuty/Config/Access Analyzer security change itself.
# After this bootstrap is applied and independently verified, ordinary remediation
# returns to the control-specific artifact only (no permanent IAM+control bundling).
#
# SECURITY:
# - Self-escalation forbidden: SentinelStacksRemediationRole MUST NOT apply this artifact
# - Scanner/planner MUST NOT apply this artifact
# - Requires explicitly authorized administrator bootstrap path
# - No wildcards (no iam:*, no guardduty:*)
# - dry_run / no auto-apply

resource "aws_iam_role_policy" "sentinel_capability_guardduty" {
  name = "SentinelGuardDutyRemediation"
  role = "SentinelStacksRemediationRole"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ManageGuarddutyRemediation",
      "Effect": "Allow",
      "Action": [
        "guardduty:CreateDetector",
        "guardduty:GetDetector",
        "guardduty:ListDetectors",
        "guardduty:UpdateDetector",
        "guardduty:TagResource",
        "guardduty:ListTagsForResource"
      ],
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "aws:RequestedRegion": "us-east-1"
        }
      }
    },
    {
      "Sid": "CreateServiceLinkedRole",
      "Effect": "Allow",
      "Action": "iam:CreateServiceLinkedRole",
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "iam:AWSServiceName": "guardduty.amazonaws.com"
        }
      }
    },
    {
      "Sid": "GetRole",
      "Effect": "Allow",
      "Action": "iam:GetRole",
      "Resource": "arn:aws:iam::952654481542:role/aws-service-role/guardduty.amazonaws.com/AWSServiceRoleForAmazonGuardDuty"
    }
  ]
}
EOF
}
